### ISSUE TITLE
pandasqt does not work for me

### ISSUE THREAD

**Issue by levicivita** [datalyze-solutions/pandas-qt#11]
I installed using pip install pandas-qt, everything worked fine.

I am following the basic example.  It fails at 
```
>>> import pandasqt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandasqt
```
The installer did create a folder `C:\Python27\Lib\site-packages\pandasqt`.  It refused to import until I added an empty __init__.py file per the [instructions from here](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-missing-init-py-trap).

**Comment by quiqua** [comment]
I'll investigate the issue and create a new pypi version as well.

**Comment by kaotika** [comment]
Does the problem still exists?

**Comment by inkenbrandt** [comment]
I think this problem has been resolved.  I installed with pip and had no problems.
```

Operating System Windows 7
Python Version 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Pandas Version 0.17.1
Numpy Version 1.10.4
Matplotlib Version 1.5.1
```
