### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by nmvasani** [datalyze-solutions/pandas-qt#13]
Apologies for such a basic and primitive question - I did "python setup.py install" and all looked great in the install (ie. no errors or issues).

Then I tried running an example: "python test app.py" that's in the examples
and received: "ImportError: No module named models.DataFrameModel"

I'm using Enthought Canopy, but I installed via terminal so this shouldn't be the issue....

**Comment by nmvasani** [comment]
I also tried the easy_install with the egg file....no issues, but same error when I try running the example!

**Comment by kaotika** [comment]
Hi, I will update the branches and the pypi package in the afternoon. I have to fix a few bugs first.
Thanks for contribution.

**Comment by kaotika** [comment]
I've fixed several bugs and updated the master branch and uploaded a new pypi package. The only problem is, that the pypi version installs even if PyQt4 is not installed.

Please keep me informed, if everything is working.
