### ISSUE TITLE
BasicExample.py is broken

### ISSUE THREAD

**Issue by waterbug** [datalyze-solutions/pandas-qt#9]
examples/BasicExample.py is broken.  One problem is that no __init__.py is installed when pandasqt is installed (using pip, at least).  Creating an empty __init__.py fixes the first error encountered (i.e., that DataFrameModel can't be found ... or anything else ;).  Next, there seems to be no setDelegatesFromDtype function defined (google search seems to indicate that it had been in __init__.py ?).

**Comment by waterbug** [comment]
s/'init.py'/'__init__.py'/

**Comment by waterbug** [comment]
Oops -- s/``init.py``/``__init__.py``/ ... stupid markdown!  :p

**Comment by quiqua** [comment]
There were some major changes to the current head and the PyPi version is currently outdated.
Will fix this as soon as possible

**Comment by kaotika** [comment]
Fixed in current develop branch

**Comment by mfreim** [comment]
Hi, just today I used pip (version 8.0.3, python 2.7.11) to install this module and I encountered the same problem of the \__init__.py being absent. It seemed like this was resolved almost a year ago though. Is there something on my end causing the problem? Thanks!

**Comment by kaotika** [comment]
Hi, I've tested it on a fresh Ubuntu 16.04 with python 2.7.11 and pip 8.0.3 and everything worked. What version of pandas-qt you installed? 0.2 or below? The bug is only fixed in the latest version.

**Comment by mfreim** [comment]
Ah okay. I installed pandas-qt 0.2.0. I'm on Windows 7. Both `pip install pandas-qt` and `pip install pip install git+https://github.com/datalyze-solutions/pandas-qt.git` gave me version 0.2.0. That seems to be the [the latest version on pypi](https://pypi.python.org/pypi/pandas-qt/0.2.0). Is there something obvious I'm missing to installing the newer version?
